name: Create a GitHub action to run the Ansible playbook


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
 

jobs:
  deployAnsible:
    runs-on: glober-runner
    steps:
    - uses: azure/docker-login@v1
      with:
          username: 'arvindrsingh'
          password: 'SIADtUJ6gf2qpOPTaFwh'
    - uses: actions/checkout@v2
    - name: Run the Ansible playbook defined in KB #13662.
      run: |
        sudo docker run --rm -t -u ubuntu talentincnyc/ansible:2.9.7py3.6 
