name: manually passing parameters

on: 
  workflow_dispatch:
    inputs:
      parameterized_user:
        description: 'user1'     
        required: true
        default: 'hello this is Shubham'
      tags:
        description: 'Test scenario tags'
jobs:
  Instance:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "parameterized_user: ${{ github.event.inputs.parameterized_user }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
